### ISSUE TITLE
Wrong Preset from conf is used 

### ISSUE THREAD

**Issue by stefano-HH** [I-Valchev/image-extension#10]
Hi,

it seems that the preset of the first image of the page is always used to render all images of that page...
The presets themselves do what they're supposed to...
If I use a different one first, it will be used for all further images.
The example is an "Imagelist" field, for "Image" fields it is a similar behavior.

**ivovalchev-imageextension.yaml**
```
productcard_big:
     widths: [ 300, 600, 900, 1000 ]
     heights: [ 300, 600, 900, 1000 ] # Optional. If heights is not set, the height will be relative to the width.
     fit: crop # Uses Bolt's `thumbnail` fit options. Pass an array, e.g. [ crop, fit, crop ] 
     class: 'productcard-big'
     sizes: ["(min-width: 1024px) 1000px", "(min-width: 680px) 900px", "(min-width: 480px) 600px", "100vw"]
     
productcard_small:
     widths: [ 300, 600 ]
     heights: [ 300, 600 ]
     fit: crop
     class: 'productcard-small'
     sizes: ["((min-width: 680px) 600px", "100vw"]
```

**twig:**
```
        {% for image in section.image %}

          {% if loop.first == true %}
            {{ responsive_image(image, 'productcard_big') }}
            <div class="grid-x grid-margin-x small-up-4">

          {% elseif loop.last == true %}
            <div class="cell last">
              {{ responsive_image(image, 'productcard_small') }}  
            </div>
            </div>      

          {% else %}
          <div class="cell">
            {{ responsive_image(image, 'productcard_small') }}  
          </div>
          {% endif %}
        {% endfor %}
```

Output HTML:
```
<img src='/files/IMG-3317.jpg' alt='Bild 1 pt' class='productcard-big' srcset='/thumbs/300×300×crop/IMG-3317.jpg 300w,/thumbs/600×600×crop/IMG-3317.jpg 600w,/thumbs/900×900×crop/IMG-3317.jpg 900w,/thumbs/1000×1000×crop/IMG-3317.jpg 1000w' sizes='(min-width: 1024px) 1000px,(min-width: 680px) 900px,(min-width: 480px) 600px,100vw' />
<div class="grid-x grid-margin-x small-up-4">


<div class="cell">
<img src='/files/IMG-3314.jpg' alt='' class='productcard-big' srcset='/thumbs/300×300×crop/IMG-3314.jpg 300w,/thumbs/600×600×crop/IMG-3314.jpg 600w,/thumbs/900×900×crop/IMG-3314.jpg 900w,/thumbs/1000×1000×crop/IMG-3314.jpg 1000w' sizes='(min-width: 1024px) 1000px,(min-width: 680px) 900px,(min-width: 480px) 600px,100vw' />  
</div>

<div class="cell">
<img src='/files/IMG-3312.jpg' alt='' class='productcard-big' srcset='/thumbs/300×300×crop/IMG-3312.jpg 300w,/thumbs/600×600×crop/IMG-3312.jpg 600w,/thumbs/900×900×crop/IMG-3312.jpg 900w,/thumbs/1000×1000×crop/IMG-3312.jpg 1000w' sizes='(min-width: 1024px) 1000px,(min-width: 680px) 900px,(min-width: 480px) 600px,100vw' />  
</div>

<div class="cell">
<img src='/files/IMG-3321.jpg' alt='' class='productcard-big' srcset='/thumbs/300×300×crop/IMG-3321.jpg 300w,/thumbs/600×600×crop/IMG-3321.jpg 600w,/thumbs/900×900×crop/IMG-3321.jpg 900w,/thumbs/1000×1000×crop/IMG-3321.jpg 1000w' sizes='(min-width: 1024px) 1000px,(min-width: 680px) 900px,(min-width: 480px) 600px,100vw' />  
</div>

 <div class="cell last">
<img src='/files/kitten.jpg' alt='' class='productcard-big' srcset='/thumbs/300×300×crop/kitten.jpg 300w,/thumbs/600×600×crop/kitten.jpg 600w,/thumbs/900×900×crop/kitten.jpg 900w,/thumbs/1000×1000×crop/kitten.jpg 1000w' sizes='(min-width: 1024px) 1000px,(min-width: 680px) 900px,(min-width: 480px) 600px,100vw' />  
</div>
</div>      
```

Updating ivovalchev/image-extension (v1.0.2 => v1.1.1)
Bolt version: 4.0.0 RC 33
and have added these changes:
https://github.com/bolt/core/pull/1679/files

 * Install type: Composer install
 * Database: sqlite 3.28.0 (without JSON)
 * PHP version: 7.2.21
 * Symfony version: v4.4.11
 * Operating System: Darwin - 18.7.0

Greetings
Stefano
